on: [push]
jobs:
  ci-tasks:
    runs-on: ubuntu-latest
    name: ci job
    steps:
      - uses: actions/checkout@v1
      - name: docker job
        id: hello
        uses: ./.github/actions/action.yaml