name: ci-instructions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    runs:
      using: 'docker'
      image: 'Dockerfile'
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - run: docker build . -f Dockerfile
      