name: ci-instructions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [14.x]
      runs:
        using: 'docker'
        image: 'Dockerfile'
      steps:
        - run: docker build . -f Dockerfile
      