name: ci-instructions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - run: echo "done"
      runs:
        using: 'docker'
        image: 'Dockerfile'
        # args:
        #   - ${{ inputs.who-to-greet }}