# on: [push]
# jobs:
#   ci-tasks:
#     runs-on: ubuntu-latest
#     name: ci job
#     steps:
#       - uses: actions/checkout@v1
#       - name: docker job
#         working-directory: ./
#         run: docker build -t node-try .

on: 
  push:
    tags: 
      - 'v*'

jobs:
  ci-tasks:
    runs-on: ubuntu-latest
    name: ci job
    steps: 
      - uses: actions/checkout@v1
      - name: release script
        working-directory: ./
        run: ./ci-source/entrypoint.sh
        env:
          NODE_AUTH_TOKEN: "SIMPLE AUTH TOKEN"
        
        # git tag -a v0.0.2 -m "upd release action"
        # git push origin v0.0.2