# on: [push]
# jobs:
#   ci-tasks:
#     runs-on: ubuntu-latest
#     name: ci job
#     steps:
#       - uses: actions/checkout@v1
#       - name: docker job
#         working-directory: ./
#         run: docker build -t node-try .

on: 
  push:
    tags: 
      - 'v*'

jobs:
  ci-tasks:
    runs-on: ubuntu-latest
    name: ci job
    steps: 
      - uses: actions/checkout@v1
      - name: release script
        working-directory: ./
        run: ./ci-source/entrypoint.sh
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          COMMITTER_NAME:  ${{ github.event.head_commit.committer.username }}
          COMMITTER_EMAIL:  ${{ github.event.head_commit.committer.email }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        
        # git tag -a v0.0.2 -m "upd release action"
        # git push origin v0.0.2